version: '3.6'

# react, backend
services:
  v9-bears-team-40:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/V9-BEARS-TEAM-40
    ports:
      - "3000:3000"


# postgres
  # postgres:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
