version: 2
jobs:
  bobby:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "Hi there." # run the `echo` command
  sally:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "Hello again!" # run the `echo` command
    workflows:
      version: 2
      bobby_and_sally_workflow:
        jobs:
          - boddy
          - sally
